### ISSUE TITLE
Windows Path Issue with H2 Example

### ISSUE THREAD

**Issue by melloware** [ulisesbocchio/jasypt-spring-boot-samples#4]
Git on Windows is failing with...

Clone: Invalid path: jasypt-spring-boot-demo-db-h2/src/main/resources/testdb:testdb.mv.db

I believe it is because testdb:testdb.mv.db is not a valid windows file name?

**Comment by ulisesbocchio** [comment]
Interesting, did the other tests work? You can omit that module if it gives you trouble

**Comment by ulisesbocchio** [comment]
fixed, give it a try

**Comment by melloware** [comment]
Thank you. I will test it out and work on my PR today.

**Comment by ulisesbocchio** [comment]
thank you buddy!

**Comment by ulisesbocchio** [comment]
@melloware any updates?

**Comment by melloware** [comment]
Its all fixed and PR was submitted here: https://github.com/ulisesbocchio/jasypt-spring-boot-samples/pull/5
